### ISSUE TITLE
Ordner für uli

### ISSUE THREAD

**Issue by ulabein** [ac-caterva/Spielwiese#2]
Servus Anja,

kannst du mir einen Ordner in der Spielwiese (Github) machen?

Gruß
Uli
PS: Hab da irgendwie keine Rechte.
Kann dich auch nicht assignen bei dem Ticket :-(

**Comment by ac-caterva** [comment]
Hab dir eine Einladung geschickt.

**Comment by ulabein** [comment]
Danke jetzt gehts.
War vorher wahrscheinlich zu dumm das ich das über die Konsole machen muss...
